name: Deploy to Firebase Hosting

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting (Dev)
        if: github.ref == 'refs/heads/develop'
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}' > firebase-service-account.json
          firebase use ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          firebase hosting:channel:deploy dev --config firebase.dev.json --expires 7d

      - name: Deploy to Firebase Hosting (Staging)
        if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}' > firebase-service-account.json
          firebase use ${{ secrets.FIREBASE_PROJECT_ID_STAGING }}
          firebase hosting:channel:deploy pr-${{ github.event.number }} --config firebase.staging.json --expires 7d

      - name: Deploy to Firebase Hosting (Production)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}' > firebase-service-account.json
          firebase use ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
          firebase hosting:channel:deploy live --only hosting --expires 30d